/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface TheTest {
    }
}
declare global {
    interface HTMLTheTestElement extends Components.TheTest, HTMLStencilElement {
    }
    var HTMLTheTestElement: {
        prototype: HTMLTheTestElement;
        new (): HTMLTheTestElement;
    };
    interface HTMLElementTagNameMap {
        "the-test": HTMLTheTestElement;
    }
}
declare namespace LocalJSX {
    interface TheTest {
    }
    interface IntrinsicElements {
        "the-test": TheTest;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "the-test": LocalJSX.TheTest & JSXBase.HTMLAttributes<HTMLTheTestElement>;
        }
    }
}
